import { AlertTriangle, Brain, CheckCircle, CircleGauge, FolderOpen, Info, RefreshCw, Zap } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { APPROVED_MODELS, hostedOptions as catalogHostedOptions, isHostedModelVerified, type HostedOption } from "../../../shared/hostedModelCatalog";
import type { CoreWorkflowSettings, EnvStatus, HostedModelVerification } from "../../lib/types";
import TooltipLabel from "../TooltipLabel";
import SetupSection from "./SetupSection";
import { useI18n } from "../../i18n";

type Props = { settings: CoreWorkflowSettings; envFile: string; envStatus: EnvStatus; verification: HostedModelVerification | null; verifying: boolean; expanded: boolean; onToggle(): void; onChange(settings: CoreWorkflowSettings): void; onEnvFile(path: string): void; onVerify(): void };

export default function HostedSettingsSection({ settings, envFile, envStatus, verification, verifying, expanded, onToggle, onChange, onEnvFile, onVerify }: Props) {
  const { t } = useI18n();
  const hosted = settings.hosted ?? { transcriptionProvider: "gemini", transcriptionModel: APPROVED_MODELS.gemini38Flash, fallbackTranscriptionProvider: "openai", fallbackTranscriptionModel: APPROVED_MODELS.openaiTranscriptionGpt, cleanupProvider: "openai", cleanupModel: APPROVED_MODELS.openaiCleanup56Luna, envFile: "" };
  function setCost(key: keyof NonNullable<CoreWorkflowSettings["cost"]>, value: number | boolean) { onChange({ ...settings, cost: { maxEstimatedApiCostUsd: 5, allowApiSpend: false, estimateCostOnly: false, ...settings.cost, [key]: value } }); }
  async function pickEnv() { const path = await window.subtitler.chooseFile(); if (path) onEnvFile(path); }
  return <>
    <SetupSection title={t("settings.hosted.apiKeys")} detail={envStatus.exists ? t("settings.hosted.keySelected") : t("settings.hosted.chooseEnv")} ready={envStatus.exists} expanded={expanded} onToggle={onToggle}>
      <label><TooltipLabel text={t("settings.hosted.envHelp")}>{t("settings.hosted.envFile")}</TooltipLabel><div className="row"><input value={envFile} onChange={(event) => onEnvFile(event.target.value)} /><button className="icon-button" onClick={pickEnv} title={t("settings.hosted.chooseEnvAria")}><FolderOpen size={17} /></button></div></label>
      <div className="status-grid"><EnvBadge label=".env" ok={envStatus.exists} /><EnvBadge label="OPENAI_API_KEY" ok={envStatus.keysPresent.OPENAI_API_KEY} /><EnvBadge label="GEMINI_API_KEY" ok={envStatus.keysPresent.GEMINI_API_KEY} /></div>
      <button onClick={onVerify} disabled={verifying || !envStatus.exists}><RefreshCw size={16} className={verifying ? "spin" : ""} /> {verifying ? t("settings.hosted.checkingApis") : t("settings.hosted.verify")}</button>
      {verification && <VerificationSummary result={verification} />}
    </SetupSection>
    <div className="stack">
      <HostedModelSelect label={t("settings.hosted.transcription")} tip={t("settings.hosted.transcriptionHelp")} options={hostedOptions(verification, "transcription")} value={`${hosted.transcriptionProvider}:${hosted.transcriptionModel}`} onChange={(provider, model) => onChange({ ...settings, hosted: { ...hosted, transcriptionProvider: provider, transcriptionModel: model } })} />
      <HostedModelSelect label={t("settings.hosted.fallback")} tip={t("settings.hosted.fallbackHelp")} options={hostedOptions(verification, "transcription")} value={`${hosted.fallbackTranscriptionProvider}:${hosted.fallbackTranscriptionModel}`} onChange={(provider, model) => onChange({ ...settings, hosted: { ...hosted, fallbackTranscriptionProvider: provider, fallbackTranscriptionModel: model } })} />
      <HostedModelSelect label={t("settings.hosted.cleanup")} tip={t("settings.hosted.cleanupHelp")} options={hostedOptions(verification, "cleanup")} value={`${hosted.cleanupProvider}:${hosted.cleanupModel}`} onChange={(provider, model) => onChange({ ...settings, hosted: { ...hosted, cleanupProvider: provider, cleanupModel: model } })} />
      <div className="two-col"><label><TooltipLabel text={t("settings.hosted.maxCostHelp")}>{t("settings.hosted.maxCost")}</TooltipLabel><input type="number" min={0} step={0.1} value={settings.cost?.maxEstimatedApiCostUsd ?? 5} onChange={(event) => setCost("maxEstimatedApiCostUsd", Number(event.target.value))} /></label><label className="check"><input type="checkbox" checked={settings.cost?.allowApiSpend ?? false} onChange={(event) => setCost("allowApiSpend", event.target.checked)} /><TooltipLabel text={t("settings.hosted.allowSpendHelp")}>{t("settings.hosted.allowSpend")}</TooltipLabel></label></div>
      <label className="check"><input type="checkbox" checked={settings.cost?.estimateCostOnly ?? false} onChange={(event) => setCost("estimateCostOnly", event.target.checked)} /><TooltipLabel text={t("settings.hosted.estimateOnlyHelp")}>{t("settings.hosted.estimateOnly")}</TooltipLabel></label>
    </div>
  </>;
}

function hostedOptions(result: HostedModelVerification | null, role: "transcription" | "cleanup"): HostedOption[] { return result ? catalogHostedOptions(role).filter((option) => isHostedModelVerified(option.provider, option.model, role, result)) : []; }
function HostedModelSelect({ label, tip, options, value, onChange }: { label: string; tip: string; options: HostedOption[]; value: string; onChange(provider: "openai" | "gemini", model: string): void }) { const { t } = useI18n(); const selected = options.find((option) => `${option.provider}:${option.model}` === value) ?? options[0]; return <label><TooltipLabel text={tip}>{label}</TooltipLabel>{options.length > 1 && selected ? <ModelDropdown options={options} selected={selected} onChange={onChange} /> : selected ? <div className="model-option-row disabled-field"><span>{selected.label}</span><ModelTraits option={selected} /></div> : <div className="disabled-field">{t("settings.hosted.verifyToSelect")}</div>}</label>; }
function ModelDropdown({ options, selected, onChange }: { options: HostedOption[]; selected: HostedOption; onChange(provider: "openai" | "gemini", model: string): void }) { const [open, setOpen] = useState(false); const root = useRef<HTMLDivElement>(null); useEffect(() => { if (!open) return; const close = (event: MouseEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, [open]); return <div className="model-dropdown" ref={root}><button type="button" className="model-dropdown-trigger" aria-haspopup="listbox" aria-expanded={open} onClick={() => setOpen(!open)}><span>{selected.label}</span><ModelTraits option={selected} /></button>{open && <div className="model-dropdown-menu" role="listbox">{options.map((option) => <button type="button" role="option" aria-selected={option.model === selected.model && option.provider === selected.provider} className="model-option-row" key={`${option.provider}:${option.model}`} onClick={() => { onChange(option.provider, option.model); setOpen(false); }}><span>{option.label}</span><ModelTraits option={option} /></button>)}</div>}</div>; }
function ModelTraits({ option }: { option: HostedOption }) { const { t } = useI18n(); const Icon = option.emphasis === "quality" ? Brain : option.emphasis === "speed" ? Zap : CircleGauge; const title = option.emphasis === "quality" ? t("settings.hosted.quality") : option.emphasis === "speed" ? t("settings.hosted.speed") : t("settings.hosted.balanced"); return <span className={`model-traits traits-${option.emphasis}`} onClick={(event) => event.stopPropagation()}><span title={title}><Icon size={16} /></span><span className="tooltip model-info" tabIndex={0}><Info size={15} /><span className="tooltip-content">{hostedModelBlurb(option, t)}</span></span></span>; }
function VerificationSummary({ result }: { result: HostedModelVerification }) { return <div className="verification-grid"><ProviderVerification label="OpenAI" result={result.openai} /><ProviderVerification label="Gemini" result={result.gemini} /></div>; }
function ProviderVerification({ label, result }: { label: string; result: HostedModelVerification["openai"] | HostedModelVerification["gemini"] }) { const { t } = useI18n(); const cleanupCount = Number(result.cleanup) + Number("cleanup37" in result && result.cleanup37) + Number("cleanup56Luna" in result && result.cleanup56Luna); const transcriptionCount = Number("transcription" in result && result.transcription) + Number("transcription38" in result && result.transcription38) + Number("transcription37" in result && result.transcription37) + Number("transcriptionGpt" in result && result.transcriptionGpt) + Number("transcription31Pro" in result && result.transcription31Pro) + Number("transcription31FlashLite" in result && result.transcription31FlashLite); const ok = transcriptionCount > 0 || cleanupCount > 0; const detail = !result.keyPresent ? t("settings.hosted.noKey") : result.error || t("settings.hosted.verificationDetail", { transcription: transcriptionCount, cleanup: cleanupCount, suffix: cleanupCount === 1 ? "" : "s" }); return <div className={ok ? "verification-ok" : "verification-failed"} role={ok ? undefined : "alert"} title={detail}>{ok ? <CheckCircle size={15} /> : <AlertTriangle size={15} />}<span><strong>{label}</strong><small>{detail}</small></span></div>; }
function EnvBadge({ label, ok }: { label: string; ok: boolean }) { return <span className={ok ? "env-ok" : "env-missing"}>{ok ? <CheckCircle size={14} /> : <AlertTriangle size={14} />}{label}</span>; }

function hostedModelBlurb(option: HostedOption, t: ReturnType<typeof useI18n>["t"]): string {
  if (option.model === APPROVED_MODELS.openaiTranscriptionGpt) return t("settings.hosted.model.openaiTranscription");
  if (option.model === APPROVED_MODELS.openaiCleanup) return t("settings.hosted.model.openaiCleanup");
  if (option.model === APPROVED_MODELS.openaiCleanup56Luna) return t("settings.hosted.model.openaiLuna");
  if (option.model === APPROVED_MODELS.gemini38Flash) return t("settings.hosted.model.gemini38");
  if (option.model === APPROVED_MODELS.gemini) return t("settings.hosted.model.gemini35");
  if (option.model === APPROVED_MODELS.gemini36Flash) return t("settings.hosted.model.gemini36");
  if (option.model === APPROVED_MODELS.gemini31Pro) return t("settings.hosted.model.gemini31Pro");
  if (option.model === APPROVED_MODELS.gemini31FlashLite) return t("settings.hosted.model.gemini31Lite");
  return option.blurb;
}
