import { AlertTriangle, Brain, CheckCircle, CircleGauge, FolderOpen, Info, RefreshCw, Zap } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { APPROVED_MODELS, hostedOptions as catalogHostedOptions, isHostedModelVerified, recommendedFallbackTranscription, type HostedOption } from "../../../shared/hostedModelCatalog";
import type { CoreWorkflowSettings, EnvStatus, HostedModelVerification } from "../../lib/types";
import TooltipLabel from "../TooltipLabel";
import SetupSection from "./SetupSection";

type Props = { settings: CoreWorkflowSettings; envFile: string; envStatus: EnvStatus; verification: HostedModelVerification | null; verifying: boolean; expanded: boolean; onToggle(): void; onChange(settings: CoreWorkflowSettings): void; onEnvFile(path: string): void; onVerify(): void };

export default function HostedSettingsSection({ settings, envFile, envStatus, verification, verifying, expanded, onToggle, onChange, onEnvFile, onVerify }: Props) {
  const hosted = settings.hosted ?? { transcriptionProvider: "gemini", transcriptionModel: APPROVED_MODELS.gemini, fallbackTranscriptionProvider: recommendedFallbackTranscription("gemini", APPROVED_MODELS.gemini).provider, fallbackTranscriptionModel: recommendedFallbackTranscription("gemini", APPROVED_MODELS.gemini).model, cleanupProvider: "openai", cleanupModel: APPROVED_MODELS.openaiCleanup, envFile: "" };
  function setCost(key: keyof NonNullable<CoreWorkflowSettings["cost"]>, value: number | boolean) { onChange({ ...settings, cost: { maxEstimatedApiCostUsd: 5, allowApiSpend: false, estimateCostOnly: false, ...settings.cost, [key]: value } }); }
  async function pickEnv() { const path = await window.subtitler.chooseFile(); if (path) onEnvFile(path); }
  return <>
    <SetupSection title="API keys" detail={envStatus.exists ? "API key file selected" : "Choose a .env file for hosted models"} ready={envStatus.exists} expanded={expanded} onToggle={onToggle}>
      <label><TooltipLabel text="Environment file containing GEMINI_API_KEY and OPENAI_API_KEY. Secret values remain in the main process and are never displayed.">.env file</TooltipLabel><div className="row"><input value={envFile} onChange={(event) => onEnvFile(event.target.value)} /><button className="icon-button" onClick={pickEnv} title="Choose .env file"><FolderOpen size={17} /></button></div></label>
      <div className="status-grid"><EnvBadge label=".env" ok={envStatus.exists} /><EnvBadge label="OPENAI_API_KEY" ok={envStatus.keysPresent.OPENAI_API_KEY} /><EnvBadge label="GEMINI_API_KEY" ok={envStatus.keysPresent.GEMINI_API_KEY} /></div>
      <button onClick={onVerify} disabled={verifying || !envStatus.exists}><RefreshCw size={16} className={verifying ? "spin" : ""} /> {verifying ? "Checking APIs" : "Verify API models"}</button>
      {verification && <VerificationSummary result={verification} />}
    </SetupSection>
    <div className="stack">
      <HostedModelSelect label="Transcription model" tip="Only verified supported transcription models are offered: OpenAI GPT-4o Transcribe or Gemini 3.5 Flash." options={hostedOptions(verification, "transcription")} value={`${hosted.transcriptionProvider}:${hosted.transcriptionModel}`} onChange={(provider, model) => onChange({ ...settings, hosted: { ...hosted, transcriptionProvider: provider, transcriptionModel: model } })} />
      <HostedModelSelect label="Fallback model" tip="Used once when the transcription model returns a malformed response. This has mostly been seen with Gemini responses that are empty, malformed, or implausibly long." options={hostedOptions(verification, "transcription")} value={`${hosted.fallbackTranscriptionProvider}:${hosted.fallbackTranscriptionModel}`} onChange={(provider, model) => onChange({ ...settings, hosted: { ...hosted, fallbackTranscriptionProvider: provider, fallbackTranscriptionModel: model } })} />
      <HostedModelSelect label="Cleanup profile" tip="Tested cleanup profiles only: GPT-5.4 mini with medium reasoning, GPT-5.6 Luna with low reasoning, or Gemini 3.5 Flash with minimal thinking." options={hostedOptions(verification, "cleanup")} value={`${hosted.cleanupProvider}:${hosted.cleanupModel}`} onChange={(provider, model) => onChange({ ...settings, hosted: { ...hosted, cleanupProvider: provider, cleanupModel: model } })} />
      <div className="two-col"><label><TooltipLabel text="Run is blocked before hosted requests when the estimated total exceeds this amount and Allow spend is off.">Max API estimate USD</TooltipLabel><input type="number" min={0} step={0.1} value={settings.cost?.maxEstimatedApiCostUsd ?? 5} onChange={(event) => setCost("maxEstimatedApiCostUsd", Number(event.target.value))} /></label><label className="check"><input type="checkbox" checked={settings.cost?.allowApiSpend ?? false} onChange={(event) => setCost("allowApiSpend", event.target.checked)} /><TooltipLabel text="Permit a hosted run even when its estimate exceeds the configured maximum. This does not itself start a run.">Allow spend</TooltipLabel></label></div>
      <label className="check"><input type="checkbox" checked={settings.cost?.estimateCostOnly ?? false} onChange={(event) => setCost("estimateCostOnly", event.target.checked)} /><TooltipLabel text="Perform audio preparation and speech selection, report the estimate, then stop before transcription and subtitle generation.">Estimate cost only</TooltipLabel></label>
    </div>
  </>;
}

function hostedOptions(result: HostedModelVerification | null, role: "transcription" | "cleanup"): HostedOption[] { return result ? catalogHostedOptions(role).filter((option) => isHostedModelVerified(option.provider, option.model, role, result)) : []; }
function HostedModelSelect({ label, tip, options, value, onChange }: { label: string; tip: string; options: HostedOption[]; value: string; onChange(provider: "openai" | "gemini", model: string): void }) { const selected = options.find((option) => `${option.provider}:${option.model}` === value) ?? options[0]; return <label><TooltipLabel text={tip}>{label}</TooltipLabel>{options.length > 1 && selected ? <ModelDropdown options={options} selected={selected} onChange={onChange} /> : selected ? <div className="model-option-row disabled-field"><span>{selected.label}</span><ModelTraits option={selected} /></div> : <div className="disabled-field">Verify API models to select</div>}</label>; }
function ModelDropdown({ options, selected, onChange }: { options: HostedOption[]; selected: HostedOption; onChange(provider: "openai" | "gemini", model: string): void }) { const [open, setOpen] = useState(false); const root = useRef<HTMLDivElement>(null); useEffect(() => { if (!open) return; const close = (event: MouseEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, [open]); return <div className="model-dropdown" ref={root}><button type="button" className="model-dropdown-trigger" aria-haspopup="listbox" aria-expanded={open} onClick={() => setOpen(!open)}><span>{selected.label}</span><ModelTraits option={selected} /></button>{open && <div className="model-dropdown-menu" role="listbox">{options.map((option) => <button type="button" role="option" aria-selected={option.model === selected.model && option.provider === selected.provider} className="model-option-row" key={`${option.provider}:${option.model}`} onClick={() => { onChange(option.provider, option.model); setOpen(false); }}><span>{option.label}</span><ModelTraits option={option} /></button>)}</div>}</div>; }
function ModelTraits({ option }: { option: HostedOption }) { const Icon = option.emphasis === "quality" ? Brain : option.emphasis === "speed" ? Zap : CircleGauge; const title = option.emphasis === "quality" ? "Quality focused" : option.emphasis === "speed" ? "Speed focused" : "Balanced"; return <span className={`model-traits traits-${option.emphasis}`} onClick={(event) => event.stopPropagation()}><span title={title}><Icon size={16} /></span><span className="tooltip model-info" tabIndex={0}><Info size={15} /><span className="tooltip-content">{option.blurb}</span></span></span>; }
function VerificationSummary({ result }: { result: HostedModelVerification }) { return <div className="verification-grid"><ProviderVerification label="OpenAI" result={result.openai} /><ProviderVerification label="Gemini" result={result.gemini} /></div>; }
function ProviderVerification({ label, result }: { label: string; result: HostedModelVerification["openai"] | HostedModelVerification["gemini"] }) { const cleanupCount = Number(result.cleanup) + Number("cleanup56Luna" in result && result.cleanup56Luna); const transcriptionCount = Number(result.transcription) + Number("transcriptionMini" in result && result.transcriptionMini) + Number("transcription31Pro" in result && result.transcription31Pro) + Number("transcription31FlashLite" in result && result.transcription31FlashLite); const ok = transcriptionCount > 0 || cleanupCount > 0; const detail = !result.keyPresent ? "No key" : result.error || `${transcriptionCount} transcription; ${cleanupCount} cleanup model${cleanupCount === 1 ? "" : "s"}`; return <div className={ok ? "verification-ok" : "verification-failed"} role={ok ? undefined : "alert"} title={detail}>{ok ? <CheckCircle size={15} /> : <AlertTriangle size={15} />}<span><strong>{label}</strong><small>{detail}</small></span></div>; }
function EnvBadge({ label, ok }: { label: string; ok: boolean }) { return <span className={ok ? "env-ok" : "env-missing"}>{ok ? <CheckCircle size={14} /> : <AlertTriangle size={14} />}{label}</span>; }
