import { contextBridge, ipcRenderer, webUtils } from "electron";
import type { AppSettings, BrollReviewDecision, EditorialSourceSelection, LlamaBackendId, MediaAnalysisDetail, MediaAnalysisScope, MediaAssetKind, MediaAssetListRequest, RunEvent, RunRequest, SilenceCutDecision, WebAssetAcquireRequest, WorkflowConfig, WorkflowName } from "../renderer/lib/types";

contextBridge.exposeInMainWorld("subtitler", {
  chooseInputFile: (defaultPath?: string) => ipcRenderer.invoke("dialog:input-file", defaultPath),
  chooseInputFiles: (defaultPath?: string) => ipcRenderer.invoke("dialog:input-files", defaultPath),
  chooseFile: () => ipcRenderer.invoke("dialog:file"),
  chooseOutputFile: (defaultPath?: string) => ipcRenderer.invoke("dialog:output-file", defaultPath),
  chooseDirectory: () => ipcRenderer.invoke("dialog:directory"),
  chooseExecutable: () => ipcRenderer.invoke("dialog:executable"),
  filePath: (file: File) => webUtils.getPathForFile(file),
  analyzeMedia: (path: string) => ipcRenderer.invoke("media:analyze", path),
  listMediaLibraryRoots: () => ipcRenderer.invoke("library:list-roots"),
  addMediaLibraryRoot: (path: string) => ipcRenderer.invoke("library:add-root", path),
  setMediaLibraryRootEnabled: (rootId: string, enabled: boolean) => ipcRenderer.invoke("library:set-root-enabled", rootId, enabled),
  removeMediaLibraryRoot: (rootId: string) => ipcRenderer.invoke("library:remove-root", rootId),
  listMediaLibraryDirectories: (rootId: string) => ipcRenderer.invoke("library:list-directories", rootId),
  setMediaLibraryDirectoryIncluded: (rootId: string, relativeDirectory: string, included: boolean) => ipcRenderer.invoke("library:set-directory-included", rootId, relativeDirectory, included),
  setMediaLibraryDirectoryVisible: (rootId: string, relativeDirectory: string, kind: "subtree" | "direct", visible: boolean) => ipcRenderer.invoke("library:set-directory-visible", rootId, relativeDirectory, kind, visible),
  setMediaLibraryDirectoryHidden: (rootId: string, relativeDirectory: string, hidden: boolean) => ipcRenderer.invoke("library:set-directory-hidden", rootId, relativeDirectory, hidden),
  removeMediaLibraryDirectoryAssets: (rootId: string, relativeDirectory: string, deleteFiles: boolean) => ipcRenderer.invoke("library:remove-directory-assets", rootId, relativeDirectory, deleteFiles),
  scanMediaLibraryRoot: (rootId: string) => ipcRenderer.invoke("library:scan", rootId),
  listMediaAssets: (request: MediaAssetListRequest) => ipcRenderer.invoke("library:list-assets", request),
  getMediaAsset: (assetId: string) => ipcRenderer.invoke("library:get-asset", assetId),
  getMediaAssetThumbnails: (assetIds: string[]) => ipcRenderer.invoke("library:thumbnails", assetIds),
  updateMediaAssetDescription: (assetId: string, description: string) => ipcRenderer.invoke("library:update-description", assetId, description),
  addMediaAssetSegment: (assetId: string, scope: MediaAnalysisScope, description: string) => ipcRenderer.invoke("library:add-segment", assetId, scope, description),
  probeWebAsset: (sourceUrl: string) => ipcRenderer.invoke("library:web-probe", sourceUrl),
  acquireWebAsset: (request: WebAssetAcquireRequest) => ipcRenderer.invoke("library:web-acquire", request),
  estimateMediaAssetAnalysis: (assetId: string, scope?: MediaAnalysisScope) => ipcRenderer.invoke("library:analysis-estimates", assetId, scope),
  planBulkMediaAnalysis: (mediaKind: MediaAssetKind | "") => ipcRenderer.invoke("library:bulk-analysis-plan", mediaKind),
  analyzeMediaAsset: (assetId: string, detail: MediaAnalysisDetail, scope?: MediaAnalysisScope) => ipcRenderer.invoke("library:analyze", assetId, detail, scope),
  cancelMediaAssetAnalysis: (assetId: string) => ipcRenderer.invoke("library:cancel-analysis", assetId),
  getAppState: () => ipcRenderer.invoke("state:get"),
  resetAppState: () => ipcRenderer.invoke("state:reset"),
  saveAppSettings: (settings: AppSettings) => ipcRenderer.invoke("state:save-settings", settings),
  getWorkflowConfig: (workflow: WorkflowName) => ipcRenderer.invoke("config:get", workflow),
  saveWorkflowConfig: (workflow: WorkflowName, config: WorkflowConfig) => ipcRenderer.invoke("config:save", workflow, config),
  getEnvStatus: (envFile: string) => ipcRenderer.invoke("env:status", envFile),
  verifyHostedModels: (envFile: string) => ipcRenderer.invoke("env:verify-hosted-models", envFile),
  listLocalProfiles: () => ipcRenderer.invoke("local-models:list"),
  getLocalModelStatus: (modelsDirectory: string, profileId: string) => ipcRenderer.invoke("local-models:status", modelsDirectory, profileId),
  downloadLocalProfile: (modelsDirectory: string, profileId: string, mode?: "direct" | "huggingface") => ipcRenderer.invoke("local-models:download", modelsDirectory, profileId, mode),
  deleteManagedLocalProfile: (modelsDirectory: string, profileId: string) => ipcRenderer.invoke("local-models:delete-managed", modelsDirectory, profileId),
  getHuggingFaceDownloaderStatus: () => ipcRenderer.invoke("local-models:hf-downloader-status"),
  installHuggingFaceDownloader: () => ipcRenderer.invoke("local-models:install-hf-downloader"),
  listLlamaBackends: () => ipcRenderer.invoke("llama:list-backends"),
  checkLatestLlamaRelease: () => ipcRenderer.invoke("llama:check-latest"),
  getManagedLlamaStatus: (backend: LlamaBackendId, releaseTag?: string) => ipcRenderer.invoke("llama:status", backend, releaseTag),
  getCurrentLlamaServerState: (serverPath: string) => ipcRenderer.invoke("llama:current-state", serverPath),
  downloadManagedLlamaServer: (backend: LlamaBackendId) => ipcRenderer.invoke("llama:download", backend),
  deleteManagedLlamaServer: (backend: LlamaBackendId) => ipcRenderer.invoke("llama:delete-managed", backend),
  readGlossary: () => ipcRenderer.invoke("glossary:read"),
  saveGlossary: (text: string) => ipcRenderer.invoke("glossary:save", text),
  importGlossary: () => ipcRenderer.invoke("glossary:import"),
  pathExists: (path: string) => ipcRenderer.invoke("path:exists", path),
  pythonReady: (path: string) => ipcRenderer.invoke("runtime:python-status", path),
  getRuntimeSetupStatus: () => ipcRenderer.invoke("runtime:setup-status"),
  createManagedPythonEnv: () => ipcRenderer.invoke("runtime:create-managed-python"),
  installPythonRequirements: () => ipcRenderer.invoke("runtime:install-python-requirements"),
  deleteManagedPythonEnv: () => ipcRenderer.invoke("runtime:delete-managed-python"),
  downloadManagedFfmpeg: () => ipcRenderer.invoke("runtime:download-ffmpeg"),
  deleteManagedFfmpeg: () => ipcRenderer.invoke("runtime:delete-ffmpeg"),
  installOrUpdateYtDlp: () => ipcRenderer.invoke("runtime:update-ytdlp"),
  deleteManagedYtDlp: () => ipcRenderer.invoke("runtime:delete-ytdlp"),
  downloadAlignmentModel: () => ipcRenderer.invoke("runtime:download-alignment"),
  deleteAlignmentModel: () => ipcRenderer.invoke("runtime:delete-alignment"),
  inspectEditorialCheckpoint: (checkpoint: string, sources?: EditorialSourceSelection[]) => sources
    ? ipcRenderer.invoke("editorial:inspect-checkpoint", checkpoint, sources)
    : ipcRenderer.invoke("editorial:inspect-checkpoint", checkpoint),
  findEditorialCheckpoint: (sources: EditorialSourceSelection[]) => ipcRenderer.invoke("editorial:find-checkpoint", sources),
  listEditorialCheckpoints: () => ipcRenderer.invoke("editorial:list-checkpoints"),
  removeEditorialCheckpoint: (checkpoint: string) => ipcRenderer.invoke("editorial:remove-checkpoint", checkpoint),
  listEditorialGames: () => ipcRenderer.invoke("editorial:list-games"),
  rememberEditorialGame: (title: string) => ipcRenderer.invoke("editorial:remember-game", title),
  startRun: (request: RunRequest) => ipcRenderer.invoke("run:start", request),
  submitSilenceReview: (runId: string, reviewId: string, decisions: Array<{ candidateId: string; decision: SilenceCutDecision }>) => ipcRenderer.invoke("run:submit-silence-review", runId, reviewId, decisions),
  submitBrollReview: (runId: string, reviewId: string, decisions: BrollReviewDecision[]) => ipcRenderer.invoke("run:submit-broll-review", runId, reviewId, decisions),
  probeCutSilenceEncoders: () => ipcRenderer.invoke("silence:probe-encoders"),
  getSilenceSource: (runId: string) => ipcRenderer.invoke("silence:source", runId),
  getSilenceProxy: (runId: string, candidateId: string, variant: "original" | "seam") => ipcRenderer.invoke("silence:proxy", runId, candidateId, variant),
  prefetchSilenceProxies: (runId: string, candidateIds: string[]) => ipcRenderer.invoke("silence:prefetch", runId, candidateIds),
  getBrollPreview: (runId: string, candidateId: string) => ipcRenderer.invoke("broll:preview", runId, candidateId),
  cancelRun: (runId: string, immediate = false) => ipcRenderer.invoke("run:cancel", runId, immediate),
  onRunEvent: (callback: (event: RunEvent) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, runEvent: RunEvent) => callback(runEvent);
    ipcRenderer.on("run:event", listener);
    return () => ipcRenderer.removeListener("run:event", listener);
  },
  openPath: (path: string) => ipcRenderer.invoke("shell:open-path", path),
  showItemInFolder: (path: string) => ipcRenderer.invoke("shell:show-item", path)
});
